sudo: required

language: generic

services:
  - docker

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.local

before_install:
- docker build --file Dockerfile-0.5 -t phlummox/carnap-build .
- docker ps -a
- docker images -a

script:
- docker --version
- docker run --rm phlummox/carnap-build stack --version

