sudo: required

language: generic

services:
  - docker

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/.local

before_install:
- docker build --file Dockerfile-0.6 -t phlummox/carnap-build:0.6 .

run:


- docker ps -a
- docker images -a

script:
- docker --version
- docker run --rm phlummox/carnap-build stack --version
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push phlummox/carnap-build:0.6

