
FROM phlummox/carnap-build:0.8

RUN \
  stack build Carnap-Server
   
RUN \
  git reset --hard && \
  git clean -fd 

COPY patches/DD-* ./

RUN \
  git checkout 2cef1d774a30d1e118d1191b374544d914740eb9 && \
  git apply DD-2cef1d774a30d1e118d1191b374544d914740eb9.patch && \
  stack build Carnap && \
  stack --stack-yaml=stack.yaml.ghcjs build Carnap && \
  stack --stack-yaml=stack.yaml.ghcjs build Carnap-GHCJS 

RUN \
  stack build Carnap-Server && \
  stack install yesod-bin


