
FROM phlummox/carnap-build:0.1

COPY patches/fix-stack-yaml ./

RUN \
  for patch in fix-stack-yaml; do \
    git apply $patch; \
  done

COPY stack.yaml.ghcjs ./

ENV TAR_OPTIONS=--no-same-owner

RUN \
  mkdir /opt/ghcjs && \
  cd /opt/ghcjs && \
  cp /opt/carnap/stack.yaml.ghcjs . && \
  stack --stack-yaml ./stack.yaml.ghcjs --allow-different-user setup



