
FROM phlummox/carnap-build:0.8

RUN \
  git reset --hard && \
  git clean -fd && \
  rm Carnap-Server/SecureStrings.hs

COPY patches/DD-* ./

RUN \
  git checkout 2cef1d774a30d1e118d1191b374544d914740eb9 && \
  git apply DD-2cef1d774a30d1e118d1191b374544d914740eb9.patch && \
  stack build Carnap && \
  stack --stack-yaml=stack.yaml.ghcjs build Carnap && \
  stack --stack-yaml=stack.yaml.ghcjs build Carnap-GHCJS 

#RUN \
#  ./mk_ghcjs_symlinks.sh && \
#  stack build Carnap-Server && \
#  stack install yesod-bin


